from fastapi import APIRouter, Depends, Response
from sqlalchemy.orm import Session
from backend.database import get_db
from backend.models.order import Order
from backend.models.bill import Bill
from weasyprint import HTML
from sqlalchemy import func
from datetime import datetime

router = APIRouter(prefix="/api/v1/print/report", tags=["print"])

@router.get("/daily")
def generate_daily_report_pdf(db: Session = Depends(get_db)):
    today = datetime.utcnow().date()

    summary = db.query(
        func.sum(Bill.total_amount).label("revenue"),
        func.count(Order.id).label("orders")
    ).join(Order, Bill.order_id == Order.id).filter(
        Bill.created_at >= today,
        Bill.status == "PAID"
    ).first()

    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: sans-serif; padding: 40px; color: #333; }}
            .header {{ border-bottom: 4px solid #c2410c; padding-bottom: 20px; margin-bottom: 40px; display: flex; justify-content: space-between; align-items: center; }}
            .logo {{ font-size: 32px; font-weight: 900; color: #c2410c; }}
            .stat-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 40px; }}
            .stat-card {{ background: #f8fafc; padding: 20px; border-radius: 12px; border: 1px solid #e2e8f0; }}
            .stat-val {{ font-size: 24px; font-weight: bold; color: #0f172a; }}
            .stat-label {{ font-size: 10px; font-weight: bold; color: #64748b; text-transform: uppercase; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th {{ text-align: left; padding: 12px; background: #f1f5f9; font-size: 12px; }}
            td {{ padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo">CHOPCORE INTELLIGENCE</div>
            <div style="text-align: right;">
                <div style="font-weight: bold;">Daily Business Review</div>
                <div style="font-size: 12px; color: #64748b;">{today.strftime('%B %d, %Y')}</div>
            </div>
        </div>

        <div class="stat-grid">
            <div class="stat-card">
                <div class="stat-label">Gross Revenue</div>
                <div class="stat-val">₵ {(summary.revenue or 0)/100:.2f}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Total Transactions</div>
                <div class="stat-val">{summary.orders or 0}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Avg. Order Value</div>
                <div class="stat-val">₵ {((summary.revenue or 0) / summary.orders / 100) if summary.orders else 0:.2f}</div>
            </div>
        </div>

        <h3>Performance Summary</h3>
        <p>This report contains automated operational data for the current business cycle. All values are in GHS.</p>

        <div style="margin-top: 60px; text-align: center; font-size: 10px; color: #94a3b8;">
            Generated by ChopCore RMS • Confidential Financial Document
        </div>
    </body>
    </html>
    """

    pdf = HTML(string=html_content).write_pdf()
    return Response(content=pdf, media_type="application/pdf")
